#!/bin/bash -


LOGIN_USER="root"


while getopts :u: opt
do
    # Check option letter
    case $opt in

    u)   LOGIN_USER=$OPTARG
         ;;

    '?') echo "$0: invalid option -$OPTARG" >&2
         echo "Usage: $0 [-u user] <Machine_List> <Commond_List>" >&2
         exit 1
         ;;

    esac
done

shift $((OPTIND - 1))


if [ $# -lt 2 ]
then
    echo "$0: invalid command parameter number" >&2
    echo "Usage: $0 [-u user] <Machine_List> <Src_Path> [Dst_Path]"
    exit 1
fi

MACHINE_LIST=$1
SrcPath=$2
DstPath=$3
SSH_POLL_TIMEOUT=10

for slave in $(cat $MACHINE_LIST)
do
    if [ $# -eq 2 ]
    then
        scp -o StrictHostKeyChecking=no          \
            -o PasswordAuthentication=no         \
            -o ConnectTimeout=$SSH_POLL_TIMEOUT  \
            -r $SrcPath $LOGIN_USER@$slave:$SrcPath &

    elif [ $# -eq 3 ]
    then
        scp -o StrictHostKeyChecking=no          \
            -o PasswordAuthentication=no         \
            -o ConnectTimeout=$SSH_POLL_TIMEOUT  \
            -r $SrcPath $LOGIN_USER@$slave:$DstPath &
    
    fi
done
wait
